Market/Market.WEB.UI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Market.Domain.Abstract;
using Market.Domain.Entities;
using Market.WEB.UI.Models;

namespace Market.WEB.UI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProductRepository r, IOrderProcessor order)
        {
            repository = r;
            orderProcessor = order;
        }
        public ViewResult Index(Cart cart, string returnURL)
        {
            return View(new CartIndexViewModel
            {
                ReturnURL = returnURL,
                cart = cart
            });
        }
        public RedirectToRouteResult AddToCArt(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if(product != null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart,int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShopingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShopingDetails shopDetails)
        {
            if(cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shopDetails);
                cart.Clear();
                return View("Completed");
            }
            
            else
            {
                return View(shopDetails);
            }
        }
    }
}

Market/Market.WEB.UI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Market.Domain.Abstract;

namespace Market.WEB.UI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        public NavController(IProductRepository r)
        {
            repository = r;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

Market/Market.WEB.UI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Market.Domain.Entities;
using Market.Domain.Abstract;
using Market.WEB.UI.Models;

namespace Market.WEB.UI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize =6;
         public ProductController(IProductRepository productRepository)
        {
            repository = productRepository;
        }
        public ViewResult List(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() :
                    repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int productID)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productID);
            if(product != null)
            {
                return File(product.ImageData, product.ImageType);
            }
            else
            {
                return null;
            }
        }
      
    }
}

Market/Market.WEB.UI/Views/Shared/ProductSummary.cshtml
@model Market.Domain.Entities.Product

<div class="row  well">
   <div class="col-sm-12">
            @if (Model.ImageData != null)
            {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="375" height="375"
                     src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
            </div>
        }

        <h3><strong>@Model.Name</strong></h3>


        <p> @Model.Description</p>
        <h5>
            <span class="pull-right label label-warning">
                @Model.Price.ToString("c")
            </span>
        </h5>
        @using (Html.BeginForm("AddToCart", "Cart"))
            {
            <div class="pull-left">
                @Html.HiddenFor(x => x.ProductID)
                @Html.Hidden("returnURL", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Добавить в корзину" />
            </div>
        }
       
    </div>
    
</div>

Market/Market.WEB.UI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
     <script src="~/Scripts/jquery-1.10.2.js"></script>
</head>
<body>
    <div>
            @if(TempData["message"] != null)
            {
                <div class="alert alert-success">@TempData["message"]</div>
            }
        </div>
    @RenderBody()
</body>
</html>

Market/Market.WEB.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Чайная лавка</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="SW">   @Html.Action("Summary", "Cart")</div> 
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu","Nav")
        </div>
        <div class="row">
        <div class="col-xs-8">
            @RenderBody()
        </div>
            </div>
    </div>
   
</body>
</html>